name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install Docker
      run: |
        sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
        
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        
        sudo apt install docker-ce docker-ce-cli containerd.io
    - name: Install ARCUS
      run: |
        # clone
        git clone https://github.com/naver/arcus.git

        # build dependencies
        cd ~/arcus

        # build server
        docker compose up -d
    - name: Build ARCUS Client
      run: mvn install -DskipTests
    - name: Test ARCUS Client
      run: mvn test -DUSE_ZK=false -DARCUS_HOST=127.0.0.1:11212 && mvn test -DUSE_ZK=true
